//AUTH ACTIONS
export const SEND_OTP_REQUEST = 'SEND_OTP_REQUEST';
export const SEND_OTP_SUCCESS = 'SEND_OTP_SUCCESS';
export const SEND_OTP_FAIL = 'SEND_OTP_FAIL';
export const SUBMIT_OTP_REQUEST = 'SUBMIT_OTP_REQUEST';
export const SUBMIT_OTP_SUCCESS = 'SUBMIT_OTP_SUCCESS';
export const SUBMIT_OTP_FAIL = 'SUBMIT_OTP_FAIL';
export const RESET_AUTH = 'RESET_AUTH';
export const SAVE_LOGIN_PHONE_NUMBER = 'SAVE_LOGIN_PHONE_NUMBER';
export const SEND_USER_LOGIN_CREDENTIALS = 'USER_LOGIN_CREDENTIALS';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const SEND_USER_SIGNUP_CREDENTIALS = 'USER_SIGNUP_CREDENTIALS';
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
export const USER_SIGNUP_FAIL = 'USER_SIGNUP_FAIL';
export const SEND_USER_LOGIN_RESET_CREDENTIALS = 'USER_LOGIN_CREDENTIALS';
export const USER_LOGIN_RESET_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_RESET_FAIL = 'USER_LOGIN_FAIL';
export const SEND_RESET_PASSWORD_CREDENTIALS =
  'SEND_RESET_PASSWORD_CREDENTIALS';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';
export const USER_SIGNUP_LOGIN_SUCCESS = 'USER_SIGNUP_LOGIN_SUCCESS'
export const LOGOUT_USER = 'LOGOUT_USER'
// USER FLOW
export const SET_USER_PROFILE = 'SET_USER_PROFILE';

//KEEL TYPES
export const SET_MENUBAR_STATE = 'SET_MENUBAR_STATE';
export const SET_AGENT_MENUBAR_STATE = 'SET_AGENT_MENUBAR_STATE';

//Task View Consumer Dashboard
export const TASK_LIST_LOADING = 'TASK_LIST_LOADING';
export const SET_TASK_LIST = 'SET_TASK_LIST';
export const TASK_DETAIL_INFO = 'TASK_DETAIL_INFO';

//AGENT TYPES

export const ADD_CASE_LIST='ADD_CASE_LIST';
export const CASE_LIST_LOADING='CASE_LIST_LOADING';

//DOCUMENT VALUT
export const DOCUMENT_LIST_LOADING = 'DOCUMENT_LIST_LOADING';
export const ADD_DOCUMENT_LIST = 'ADD_DOCUMENT_LIST';

//CHAT
export const CHAT_LOADING = 'CHAT_LOADING';
export const MERGE_CHAT_MESSAGES = 'MERGE_CHAT_MESSAGES';

export const GET_USER_PROFILE = 'GET_USER_PROFILE';
export const LOADING_USER_PROFILE = 'LOADING_USER_PROFILE';
export const GET_FULL_USER_PROFILE = 'GET_FULL_USER_PROFILE';
export const LOADING_FULL_USER_PROFILE = 'LOADING_FULL_USER_PROFILE';
export const UPDATE_USER_PROFILE = 'UPDATE_USER_PROFILE';

export const SAVE_PLACE_INFO = 'SAVE_PLACE_INFO';
export const SAVE_SHORT_PROFILE_INFO = 'SAVE_SHORT_PROFILE_INFO';
export const AGENT_LOGIN_SUCCESS = 'AGENT_LOGIN_SUCCESS';
export const SET_ACTIVE_TASK = 'SET_ACTIVE_TASK';
//CUSTOMER DETAILS

export const CASE_DETAIL_LOADING = 'CASE_DETAIL_LOADING';
export const CASE_DETAILS  = 'CASE_DETAILS';

//CALENDLY 
export const CALENDLY_URL_LOADING = 'CALENDLY_URL_LOADING';
export const FETCH_CALENDLY_URL = 'FETCH_CALENDLY_URL';
export const GET_SCHEDULE_DETAIL = 'GET_SCHEDULE_DETAIL'

//AGENT PROFILE
export const FETCH_AGENT_PROFILE = 'FETCH_AGENT_PROFILE';
export const AGENT_PROFILE_LOADING = 'AGENT_PROFILE_LOADING';

//AGENT CALENDLY
export const AGENT_SCHEDULE_LOADING = 'AGENT_SCHEDULE_LOADING';
export const AGENT_SCHEDULE_DETAILS = 'AGENT_SCHEDULE_DETAILS';
export const FETCH_COUNTRY_LIST = 'FETCH_COUNTRY_LIST';

export const GET_PLAN_COMPONENT = 'GET_PLAN_COMPONENT';
export const FETCH_NOTIFICATION = 'FETCH_NOTIFICATION';
export const TOGGLE_NOTIFICATION_CHAT = 'TOGGLE_NOTIFICATION_CHAT';
export const NOTIFICATION_LOADING = 'NOTIFICATION_LOADING';

//TEMPLATE
export const FETCH_TEMPLATE_LIST_LOADING = 'FETCH_TEMPLATE_LIST_LOADING';
export const FETCH_TEMPLATE_LIST = 'FETCH_TEMPLATE_LIST';

//Agent Notification 
export const AGENT_NOTIFICATION_LOADING = 'AGENT_NOTIFICATION_LOADING';
export const AGENT_NOTIFICATION_INFO = 'AGENT_NOTIFICATION_INFO';