
//AUTH ACTIONS
export const SEND_OTP_REQUEST = 'SEND_OTP_REQUEST'
export const SEND_OTP_SUCCESS = 'SEND_OTP_SUCCESS'
export const SEND_OTP_FAIL = 'SEND_OTP_FAIL'
export const SUBMIT_OTP_REQUEST = 'SUBMIT_OTP_REQUEST'
export const SUBMIT_OTP_SUCCESS = 'SUBMIT_OTP_SUCCESS'
export const SUBMIT_OTP_FAIL = 'SUBMIT_OTP_FAIL'
export const RESET_AUTH = 'RESET_AUTH'
export const SAVE_LOGIN_PHONE_NUMBER = 'SAVE_LOGIN_PHONE_NUMBER'

// USER FLOW
export const SET_USER_PROFILE = 'SET_USER_PROFILE'




//KEEL TYPES
export const SET_MENUBAR_STATE = 'SET_MENUBAR_STATE';