//AUTH ACTIONS
export const SEND_OTP_REQUEST = 'SEND_OTP_REQUEST';
export const SEND_OTP_SUCCESS = 'SEND_OTP_SUCCESS';
export const SEND_OTP_FAIL = 'SEND_OTP_FAIL';
export const SUBMIT_OTP_REQUEST = 'SUBMIT_OTP_REQUEST';
export const SUBMIT_OTP_SUCCESS = 'SUBMIT_OTP_SUCCESS';
export const SUBMIT_OTP_FAIL = 'SUBMIT_OTP_FAIL';
export const RESET_AUTH = 'RESET_AUTH';
export const SAVE_LOGIN_PHONE_NUMBER = 'SAVE_LOGIN_PHONE_NUMBER';
export const SEND_USER_LOGIN_CREDENTIALS = 'USER_LOGIN_CREDENTIALS';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const SEND_USER_SIGNUP_CREDENTIALS = 'USER_SIGNUP_CREDENTIALS';
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
export const USER_SIGNUP_FAIL = 'USER_SIGNUP_FAIL';
export const SEND_USER_LOGIN_RESET_CREDENTIALS = 'USER_LOGIN_CREDENTIALS';
export const USER_LOGIN_RESET_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_RESET_FAIL = 'USER_LOGIN_FAIL';
export const SEND_RESET_PASSWORD_CREDENTIALS =
  'SEND_RESET_PASSWORD_CREDENTIALS';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';

// USER FLOW
export const SET_USER_PROFILE = 'SET_USER_PROFILE';

//KEEL TYPES
export const SET_MENUBAR_STATE = 'SET_MENUBAR_STATE';
export const SET_AGENT_MENUBAR_STATE = 'SET_AGENT_MENUBAR_STATE';

//Task View Consumer Dashboard
export const TASK_LIST_LOADING = 'TASK_LIST_LOADING';
export const SET_TASK_LIST = 'SET_TASK_LIST';
export const TASK_DETAIL_INFO = 'TASK_DETAIL_INFO';

//AGENT TYPES

export const ADD_CASE_LIST='ADD_CASE_LIST';
export const CASE_LIST_LOADING='CASE_LIST_LOADING';

//DOCUMENT VALUT
export const DOCUMENT_LIST_LOADING = 'DOCUMENT_LIST_LOADING';
export const ADD_DOCUMENT_LIST = 'ADD_DOCUMENT_LIST';

//CHAT
export const CHAT_LOADING = 'CHAT_LOADING';
export const MERGE_CHAT_MESSAGES = 'MERGE_CHAT_MESSAGES';

export const GET_USER_PROFILE = 'GET_USER_PROFILE';
export const LOADING_USER_PROFILE = 'LOADING_USER_PROFILE';
export const GET_FULL_USER_PROFILE = 'GET_FULL_USER_PROFILE';
export const LOADING_FULL_USER_PROFILE = 'LOADING_FULL_USER_PROFILE';
export const UPDATE_USER_PROFILE = 'UPDATE_USER_PROFILE';

export const SAVE_PLACE_INFO = 'SAVE_PLACE_INFO';
export const SAVE_SHORT_PROFILE_INFO = 'SAVE_SHORT_PROFILE_INFO';
export const AGENT_LOGIN_SUCCESS = 'AGENT_LOGIN_SUCCESS';
